name: Print Resume & Deploy to GH Pages

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build Hugo
        uses: srt32/hugo-action@v0.0.3

      - name: Install node dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install --production=true

      - name: Print Resume
        run: node print.js

      - uses: EndBug/add-and-commit@v7
        with:
          message: 'Updated resume print from pipeline'

      - name: GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          disable_nojekyll: true
